### ISSUE TITLE
Trigger crash: event without signals

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/pax#383]
```
Traceback (most recent call last):
  File "/home/xedaq/anaconda3/envs/pax/bin/event-builder", line 4, in <module>
    __import__('pkg_resources').run_script('pax==5.0.0', 'event-builder')
  File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/setuptools-20.6.7-py3.4.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/setuptools-20.6.7-py3.4.egg/pkg_resources/__init__.py", line 1483, in run_script
  File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-5.0.0-py3.4.egg/EGG-INFO/scripts/event-builder", line 308, in <module>
    main()
  File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-5.0.0-py3.4.egg/EGG-INFO/scripts/event-builder", line 177, in main
    p.run()     # The run() method includes a call to shutdown()
  File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-5.0.0-py3.4.egg/pax/core.py", line 512, in run
    for i, event in enumerate(self.get_events()):
  File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-5.0.0-py3.4.egg/pax/plugins/io/MongoDB.py", line 313, in get_events
    last_data=(not more_data_coming and i == len(futures) - 1)):
  File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-5.0.0-py3.4.egg/pax/trigger.py", line 180, in run
    plugin.process(data)
  File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-5.0.0-py3.4.egg/pax/trigger_plugins/SaveSignals.py", line 14, in process
    group_signals(data.signals, data.event_ranges, sig_idx, is_in_event)
ValueError: Error during signal grouping: event without signals??
```

**Comment by JelleAalbers** [comment]
This has been resolved in 54ea7b177a3391cc314ab2484c016d9843c07ab1, it was due to invalid trigger settings accidentally introduced in #372. #388 will prevent this from occurring again.
