### ISSUE TITLE
run time error for the new pax > 6.0.2

### ISSUE THREAD

**Issue by feigaodm** [XENON1T/pax#448]
Patrick and I found an run time error in the current master. The error appears after we load pax_head and use paxer. The local installation of pax also has the same problem.  

```
Traceback (most recent call last):
  File "bin/paxer", line 4, in <module>
    __import__('pkg_resources').run_script('pax==6.0.2', 'paxer')
  File "/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/setuptools-20.3-py3.4.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/setuptools-20.3-py3.4.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/home/feigao/analysis/xe1t/pax/pax/lib/python3.4/site-packages/pax-6.0.2-py3.4.egg/EGG-INFO/scripts/paxer", line 4, in <module>

.........

File "/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/setuptools-20.3-py3.4.egg/pkg_resources/_vendor/pyparsing.py", line 1005, in _parseNoCache
    return self
  File "/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/setuptools-20.3-py3.4.egg/pkg_resources/_vendor/pyparsing.py", line 1885, in parseImpl
    self.initChars = set(initChars)
  File "/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/setuptools-20.3-py3.4.egg/pkg_resources/_vendor/pyparsing.py", line 278, in __new__
    # Performance tuning: we construct a *lot* of these, so keep this
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by JelleAalbers** [comment]
Thanks Fei, this looks like a bug in one of our dependencies. I've never seen it before. Could you post the entire error trace either here or in a gist?

**Comment by feigaodm** [comment]
How about the updated one? The errors are repeating this information.

**Comment by JelleAalbers** [comment]
Thanks, unfortunately I have no idea what's going on, especially since you see it in independent setups, yet the builds are passing on our TravisCI test server (I just re-ran the last build to verify). Does `import pax` work for you?

**Comment by feigaodm** [comment]
Thanks Jelle, I guess then it's my problem of installing pax locally on midway. Could you please give me some guidance on how to install and develop pax on midway?

**Comment by tunnell** [comment]
There are instructions on installing pax here:

https://github.com/XENON1T/pax/blob/master/README.rst

This is our automated procedure that we check each commit:

https://github.com/XENON1T/pax/blob/master/.travis.yml#L64

If you can reproduce the problem, please post via gist.github.com the error you see so we can reproduce.

**Comment by feigaodm** [comment]
I tried the following command to create my own env for pax on midway:
'''
   conda env create -f /project/lgrandi/deployHQ/head.yml -n pax_for_fei
'''
then I met the permission issue. What should I proceed to create the env for pax?


'''
Using Anaconda API: https://api.anaconda.org
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............
Solving package specifications .............
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 318, in ensure_linked_actions
    os.makedirs(ppath)
  File "/project/lgrandi/anaconda3/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/project/lgrandi/anaconda3/pkgs/cloog-0.18.0-0/info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/lgrandi/anaconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 100, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 16, in install
    actions = plan.install_actions(prefix, index, specs, prune=prune)
  File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 461, in install_actions
    shortcuts=shortcuts)
  File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 333, in ensure_linked_actions
    actions[inst.LINK].append(dist, LINK_COPY, shortcuts)
TypeError: append() takes exactly one argument (3 given)
'''

**Comment by tunnell** [comment]
That command isn't in the instructions.  Try the instructions and make sure you don't have another conda environment activate (i.e. 'conda' should give no command found).

**Comment by pdeperio** [comment]
Ah, you want him to install his own Anaconda? We were trying to use the common anaconda environment to avoid this step and save some disk space. There isn't some way for users to create their own environment locally?

**Comment by JelleAalbers** [comment]
@feigaodm Has this issue been solved?

**Comment by feigaodm** [comment]
@JelleAalbers  After installation of my own Anaconda and then pax, I don't have this problem anymore.

**Comment by JelleAalbers** [comment]
Thanks
