### ISSUE TITLE
Pax pax_rcCRfD crashed (7.11 - 20:30)

### ISSUE THREAD

**Issue by sdiglio** [XENON1T/pax#451]
7.11 - 8:30 pm

Trigger not responding

DAQ stopped

Happening at the end of AmBe run 161107_1829 (4394) 

Pax pax_rcCRfD crashed! 
Traceback: Traceback (most recent call last): File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-6.0.2-py3.4.egg/pax/parallel.py", line 356, in safe_processor Processor(**kwargs) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-6.0.2-py3.4.egg/pax/core.py", line 186, in __init__ self.run() File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-6.0.2-py3.4.egg/pax/core.py", line 325, in run self.shutdown() File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-6.0.2-py3.4.egg/pax/core.py", line 383, in shutdown ap.shutdown() File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-6.0.2-py3.4.egg/pax/plugins/io/MongoDB.py", line 645, in shutdown self.drop_collection_named(db, coll_name) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-6.0.2-py3.4.egg/pax/plugins/io/MongoDB.py", line 694, in drop_collection_named self.rescue_acquisition_monitor_pulses(db[collection_name]) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pax-6.0.2-py3.4.egg/pax/plugins/io/MongoDB.py", line 673, in rescue_acquisition_monitor_pulses n_to_rescue = collection.count(query) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pymongo/collection.py", line 1235, in count return self._count(cmd) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pymongo/collection.py", line 1199, in _count read_concern=self.read_concern) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pymongo/collection.py", line 205, in _command read_concern=read_concern) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pymongo/pool.py", line 213, in command read_concern) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pymongo/network.py", line 99, in command helpers._check_command_response(response_doc, None, allowable_errors) File "/home/xedaq/anaconda3/envs/pax/lib/python3.4/site-packages/pymongo/helpers.py", line 196, in _check_command_response raise OperationFailure(msg % errmsg, code, response) pymongo.errors.OperationFailure: Exec error: OperationFailed: Operation aborted because: all indexes on collection dropped, state: DEAD

**Comment by tunnell** [comment]
Small bits of information since we don't have time to fix today:

There are many mongo collections lingering and another error post:  https://gist.github.com/tunnell/35b1d3db96c93c4f757dcb321943ea51

paxmaker through error on eb0.

event-builder process stopped on eb0.

Run 4395, where it crashed a minute in.  Hypothesis a race condition on clearing collections before they are actually finished.

**Comment by JelleAalbers** [comment]
Thanks Sara and Chris, you're right this is sort of a race condition, though not specifically due to pax multiprocessing. Technical details are in the commit above; this should prevent it from recurring.
