### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#470]
Getting a lot of this error when processing MC on OSG. I cannot reproduce on Midway, but do you have any idea why looking at the error message? I thought I'm running in single-thread mode, so why's it mentioning all this multi-thread/dask stuff?
```
/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/bin/paxer", line 4, in <module>
    __import__('pkg_resources').run_script('pax==6.1.1', 'paxer')
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/pax-6.1.1-py3.4.egg/EGG-INFO/scripts/paxer", line 24, in <module>
    from pax import core, utils, formats, parallel    # flake8: noqa
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/pax-6.1.1-py3.4.egg/pax/core.py", line 16, in <module>
    from pax import simulation, utils
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/pax-6.1.1-py3.4.egg/pax/simulation.py", line 13, in <module>
    import multihist    # noqa   # Not explicitly used, but pickle of gas gap warping map is in this format
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/multihist-0.5.0-py3.4.egg/multihist.py", line 22, in <module>
    import dask
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/dask/__init__.py", line 7, in <module>
    from .delayed import do, delayed, value
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/dask/delayed.py", line 13, in <module>
    from . import threaded
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/site-packages/dask/threaded.py", line 22, in <module>
    default_pool = ThreadPool()
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/multiprocessing/pool.py", line 761, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/pax_v6.1.1/lib/python3.4/threading.py", line 841, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by JelleAalbers** [comment]
One of pax's dependencies (multihist) tries to load an optional dependency (dask) which apparently has a problem starting up. I've released a new version of multihist that should handle this problem gracefully  (whatever it is), if you update it with pip this should be resolved. If you want to test it, you can seen if `import multihist` succeeds.

**Comment by pdeperio** [comment]
OK thanks, I've installed ```v0.5.1``` and will try again after OSG is back up.
