### ISSUE TITLE
fax MemoryError with MC input

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#474]
We (@dlingling, @JoernMahlstedt, @mrcselvi) have found that fax is frequently throwing the following ```MemoryError``` in a significant number of MC jobs:
```
Traceback (most recent call last):
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/bin/paxer", line 4, in <module>
    __import__('pkg_resources').run_script('pax==6.2.0', 'paxer')
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/setuptools-20.3-py3.4.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/setuptools-20.3-py3.4.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/pax-6.2.0-py3.4.egg/EGG-INFO/scripts/paxer", line 290, in <module>
    main()
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/pax-6.2.0-py3.4.egg/EGG-INFO/scripts/paxer", line 116, in main
    parallel.maybe_multiprocess(args, **config_kwargs)
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/pax-6.2.0-py3.4.egg/pax/parallel.py", line 165, in maybe_multiprocess
    pax_instance.run()
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/pax-6.2.0-py3.4.egg/pax/core.py", line 310, in run
    total=self.number_of_events)):
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/tqdm-4.10.0-py3.4.egg/tqdm/_tqdm.py", line 816, in __iter__
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/pax-6.2.0-py3.4.egg/pax/plugins/io/WaveformSimulator.py", line 247, in get_events
    yield self.simulate_single_event(instructions)
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/pax-6.2.0-py3.4.egg/pax/plugins/io/WaveformSimulator.py", line 221, in simulate_single_event
    event = self.simulator.make_pax_event()
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/pax-6.2.0-py3.4.egg/pax/simulation.py", line 323, in make_pax_event
    current_wave = np.zeros(pulse_length)
MemoryError
```
reproducible on Midway with:
```
export PATH="/project/lgrandi/anaconda3/bin:$PATH"
source activate pax_v6.2.0
paxer --input /project/lgrandi/jialing/Xenon1T_WholeLXe_Rn220_00499_g4mc_NEST_Patch.root --config XENON1T reduce_raw_data SimulationMCInput --output test --event 1
```

Comparing the tree scans between an input file with no problem (```Xenon1T_AmBe_neutronISO_00001_g4mc_G4_Sort.root ```) and the offending file (```Xenon1T_WholeLXe_Rn220_00499_g4mc_NEST_Patch.root ```) below, I see the main difference is in the much larger ```Fax_t``` parameter. @mcfatelin, @JelleAalbers any idea if and why this might cause a crash? (If fax can't handle this, then we'll have to fix ```Fax_t``` on the MC/Patch side.) 

```
root -b /project/lgrandi/jialing/Xenon1T_AmBe_neutronISO_00001_g4mc_G4_Sort.root  # Successful
events->cd()
events->Scan("Fax_nph:Fax_nel:Fax_nr:Fax_t:Fax_x:Fax_y:Fax_z","","colsize=10")
******************************************************************************************************************
*    Row   * Instance *    Fax_nph *    Fax_nel *     Fax_nr *      Fax_t *      Fax_x *      Fax_y *      Fax_z *
******************************************************************************************************************
*        0 *        0 *         12 *          0 *          0 *          0 * 375.613098 * 292.869354 * -555.75537 *
*        0 *        1 *       1695 *        825 *          0 * 4.7293e-11 * 368.165191 * 281.251556 * -552.56054 *
```

```
root -b /project/lgrandi/jialing/Xenon1T_WholeLXe_Rn220_00499_g4mc_NEST_Patch.root  # MemoryError
events->cd()
events->Scan("Fax_nph:Fax_nel:Fax_nr:Fax_t:Fax_x:Fax_y:Fax_z","","colsize=10")
******************************************************************************************************************
*    Row   * Instance *    Fax_nph *    Fax_nel *     Fax_nr *      Fax_t *      Fax_x *      Fax_y *      Fax_z *
******************************************************************************************************************
*        0 *        0 *            *            *            *            *            *            *            *
*        1 *        0 *       4964 *       3895 *          0 * 43083.7421 * 399.530944 * -118.80814 * -414.60095 *
```

**Comment by JelleAalbers** [comment]
Hi, Fax_t is interpreted as the time in seconds between the start of the simulated event and where this interaction takes place. If you put this at 40 thousand, you're instructing fax to produce an event that is at least 40 thousand seconds long (during which it will simulate noise, which is later passed through a self-trigger emulation). To build the waveform, fax starts trying to allocate an array of 40e3 s / 10 ns = 4e12 floats, which would take several terabytes of memory. Hence the MemoryError.

So it looks like a misunderstanding between the MC script and fax on the meaning of time. Maybe you're inputting the absolute time since the start of the run rather than since the start of an event.

(Thanks a lot for reporting the issue in such detail by the way! Maybe for next time: I usually only apply the 'bug' tag after I know there is some code in pax that's malfunctioning and needs to be fixed.)

**Comment by pdeperio** [comment]
This issue was moved to XENON1T/mc#17
