### ISSUE TITLE
Not all peaks have at least 1 channel

### ISSUE THREAD

**Issue by ershockley** [XENON1T/pax#497]
While processing with 6.3.1, see the error below for several runs. Pax is called using the cax-process command, found here [https://github.com/XENON1T/cax/blob/OSG_dev2/cax/tasks/process.py#L32](url). An example is run 4459, in particular at event 934 of this zip file: XENON1T-4459-000029000-000029999-000001000.zip. 

`Traceback (most recent call last):
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/bin/cax-process", line 11, in <module>
    load_entry_point('cax==4.10.4', 'console_scripts', 'cax-process')()
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/lib/python3.4/site-packages/cax-4.10.4-py3.4.egg/cax/tasks/process.py", line 348, in main
    _process(*sys.argv[1:])
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/lib/python3.4/site-packages/cax-4.10.4-py3.4.egg/cax/tasks/process.py", line 155, in _process
    core.Processor(**pax_kwargs).run()
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/lib/python3.4/site-packages/pax-6.3.1-py3.4.egg/pax/core.py", line 315, in run
    self.process_event(event)
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/lib/python3.4/site-packages/pax-6.3.1-py3.4.egg/pax/core.py", line 276, in process_event
    event = plugin.process_event(event)
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/lib/python3.4/site-packages/pax-6.3.1-py3.4.egg/pax/plugin.py", line 91, in process_event
    event = self._process_event(event)
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/lib/python3.4/site-packages/pax-6.3.1-py3.4.egg/pax/plugin.py", line 108, in _process_event
    return self.transform_event(event)
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/lib/python3.4/site-packages/pax-6.3.1-py3.4.egg/pax/plugins/signal_processing/BuildPeaks.py", line 30, in transform_event
    detector=detector))
  File "/cvmfs/xenon.opensciencegrid.org/releases/anaconda/2.4/envs/evan-testing/lib/python3.4/site-packages/pax-6.3.1-py3.4.egg/pax/plugin.py", line 176, in build_peak
    raise RuntimeError("Every peak should have at least one contributing channel... what's going on?")
RuntimeError: Every peak should have at least one contributing channel... what's going on?`

**Comment by feigaodm** [comment]
@ershockley Is this error still occuring? Otherwise close the issue? Thanks
