### ISSUE TITLE
Environment creation on Midway (wheel.py error)

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#552]
Trying to create a new conda environment for pax on Midway with e.g.:
```
conda env create -f /project/lgrandi/deployHQ/head.yml -n pax_v6.2.1
```
results in error:
```
Exception:
Traceback (most recent call last):
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.1/lib/python3.4/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.1/lib/python3.4/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.1/lib/python3.4/site-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.1/lib/python3.4/site-packages/pip/req/req_install.py", line 835, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.1/lib/python3.4/site-packages/pip/req/req_install.py", line 1030, in move_wheel_files
    isolated=self.isolated,
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.1/lib/python3.4/site-packages/pip/wheel.py", line 344, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.1/lib/python3.4/site-packages/pip/wheel.py", line 328, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted
```

[This pip issue](https://github.com/pypa/pip/issues/2125) suggests it's due to multiple users installing in the same ```anaconda3``` folder.

Not sure what the best solution is right now; maybe just nuke it and reinstall everything again and make sure nobody else installs in there.

Until the issue is solved, use the following command (which ensures you take the versions from the NLeSC channel) for creating new environments:
```
PAX_VERSION=v6.2.1
conda create -n pax_${PAX_VERSION} python=3.4 root=6 numpy scipy=0.18.1 pyqt=4.11 matplotlib pandas cython h5py numba pip python-snappy pytables scikit-learn rootpy pymongo psutil jupyter dask root_pandas jpeg=8d isl=0.12.2 gmp=5.1.2 glibc=2.12.2 graphviz=2.38.0=4 gsl=1.16 linux-headers=2.6.32 mpc=1.0.1 mpfr=3.1.2 pcre=8.37 python-snappy=0.5 pyopenssl=0.15.1

ln /project/lgrandi/anaconda3/envs/pax_head/etc/conda/activate.d/*.sh  /project/lgrandi/anaconda3/envs/pax_${PAX_VERSION}/etc/conda/activate.d/.
```

**Comment by lucrlom** [comment]
I'm not sure that root=6 is a good version. I knew that it was still under development version. I suggest to use root=5.34

**Comment by pdeperio** [comment]
where do you see that? should be stable, we've been using it since the beginning thanks to a lot of work from @remenska to make it work with pax/Python

**Comment by tunnell** [comment]
Is it still under development?  This isn't really pax....

**Comment by tunnell** [comment]
@pdeperio can you update README?
